"""empty message

Revision ID: a57aeac2d30f
Revises: c9de3086e832
Create Date: 2025-07-03 12:56:35.891226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a57aeac2d30f'
down_revision: Union[str, None] = 'c9de3086e832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slack_username', sa.String(), nullable=False),
    sa.Column('slack_user_id', sa.String(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('stage', sa.Enum('one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'bonus', name='stageenum'), nullable=False),
    sa.Column('track', sa.Enum('backend', 'frontend', 'design', 'devops', 'data_analysis', 'project_management', name='trackenum'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('uploader_id', sa.String(), nullable=False),
    sa.Column('uploader_username', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_id'), 'scores', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scores_id'), table_name='scores')
    op.drop_table('scores')
    # ### end Alembic commands ###
